# Generated by Django 3.2.6 on 2021-08-10 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import persons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=persons.models.get_person_avatar_path)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('mobile_confirmed', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
