# Generated by Django 3.2.6 on 2021-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
